version: '3'

services:
  elasticsearch:
    image: sinatra/elasticsearch
    build:
      context: ./elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ES_PORT: "9200"
      ES_DATA_DIR: "${RACK_ENV}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data/${ES_DATA_DIR}/:/usr/share/elasticsearch/data/${ES_DATA_DIR}
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  db:
    image: sinatra/psql
    ports:
     - 5432:5432
    build:
      context: ./psql
    volumes:
      - ./psql/data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ruby_geolocation_${RACK_ENV}
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always

  ruby:
    image: sinatra/ruby
    environment:
      MS_UID: ${UID}
      MS_GID: ${UID}
      RACK_ENV: ${RACK_ENV}
      APP_HOME: /web
    build: 
      context: ./ruby
    entrypoint: /usr/src/ruby-entrypoint.sh
    volumes:
      - ./web:/web:cached
      - ./ruby/bundle_cache:/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - db
    links:
      - elasticsearch
      - db
    restart: always