source 'http://rubygems.org'

# server
gem 'puma'

# sinatra dependencies
gem 'activerecord', '~> 5.2.1'
gem 'pg', '1.1.3'
gem 'rake', '~> 10.3'

gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib'
gem 'sinatra-activerecord', '~> 2.0'
gem 'json'
gem 'rack-parser', require: 'rack/parser'

gem 'elasticsearch', '6.0.2'
gem 'elasticsearch-model', '5.0.0'
gem 'elasticsearch-persistence', '5.0.0', require: 'elasticsearch/persistence/model'

group :development, :test do
  gem 'byebug'
  gem 'guard-rspec', require: false
  gem 'webmock'
end

group :test do
  gem 'ruby-prof'
  gem 'factory_girl', '4.3.0'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'simplecov', :require => false
end